@echo off
REM Script pour nettoyer et archiver la documentation obsolète
REM Usage: cleanup_docs.bat

echo ========================================
echo   Nettoyage Documentation
echo ========================================
echo.

set ARCHIVE_DIR=documentation\archive
set ROOT_DIR=.

REM Créer répertoire archive si nécessaire
if not exist "%ARCHIVE_DIR%" (
    mkdir "%ARCHIVE_DIR%"
    echo Répertoire archive créé: %ARCHIVE_DIR%
)

echo.
echo Déplacement fichiers obsolètes vers archive...
echo.

REM Fichiers de complétion/sessions à archiver
if exist "%ROOT_DIR%\ACTIVATION_COMPLETE_SUMMARY.md" move "%ROOT_DIR%\ACTIVATION_COMPLETE_SUMMARY.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\ACTIVATION_FONCTIONNALITES_AVANCEES.md" move "%ROOT_DIR%\ACTIVATION_FONCTIONNALITES_AVANCEES.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\ARCHITECTURE_SIMULATORS_REALTIME.md" move "%ROOT_DIR%\ARCHITECTURE_SIMULATORS_REALTIME.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\CLEANUP_OBSOLETE_DIRS.md" move "%ROOT_DIR%\CLEANUP_OBSOLETE_DIRS.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\COMPLETION_FINALE_IA.md" move "%ROOT_DIR%\COMPLETION_FINALE_IA.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\DEVELOPMENT_COMPLETE_REPORT.md" move "%ROOT_DIR%\DEVELOPMENT_COMPLETE_REPORT.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\DOCKER_FIX_SUMMARY.md" move "%ROOT_DIR%\DOCKER_FIX_SUMMARY.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\FINAL_STATUS.md" move "%ROOT_DIR%\FINAL_STATUS.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\FIX_EURALIS_FRONTEND_ERRORS.md" move "%ROOT_DIR%\FIX_EURALIS_FRONTEND_ERRORS.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\FONCTIONNALITES_AVANCEES_STATUS.md" move "%ROOT_DIR%\FONCTIONNALITES_AVANCEES_STATUS.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\INDEX_DOCUMENTATION.md" move "%ROOT_DIR%\INDEX_DOCUMENTATION.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\INDEX_SIMULATORS_ML.md" move "%ROOT_DIR%\INDEX_SIMULATORS_ML.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\INTEGRATION_COMPLETE_FINALE.md" move "%ROOT_DIR%\INTEGRATION_COMPLETE_FINALE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\INTEGRATION_SIMULATORS_SUMMARY.md" move "%ROOT_DIR%\INTEGRATION_SIMULATORS_SUMMARY.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\INTEGRATION_SQAL_BACKEND.md" move "%ROOT_DIR%\INTEGRATION_SQAL_BACKEND.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\KEYCLOAK_AUTO_SETUP.md" move "%ROOT_DIR%\KEYCLOAK_AUTO_SETUP.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\KEYCLOAK_CONFIGURATION_GUIDE.md" move "%ROOT_DIR%\KEYCLOAK_CONFIGURATION_GUIDE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\KEYCLOAK_INTEGRATION_COMPLETE.md" move "%ROOT_DIR%\KEYCLOAK_INTEGRATION_COMPLETE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\KEYCLOAK_SECURITY_GUIDE.md" move "%ROOT_DIR%\KEYCLOAK_SECURITY_GUIDE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\KEYCLOAK_SECURITY_IMPLEMENTATION.md" move "%ROOT_DIR%\KEYCLOAK_SECURITY_IMPLEMENTATION.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\LOGGING_IMPLEMENTATION_COMPLETE.md" move "%ROOT_DIR%\LOGGING_IMPLEMENTATION_COMPLETE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\LOGGING_SYSTEM_GUIDE.md" move "%ROOT_DIR%\LOGGING_SYSTEM_GUIDE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\MIGRATION_BACKEND_PARTAGE.md" move "%ROOT_DIR%\MIGRATION_BACKEND_PARTAGE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\ML_ALGORITHMS_STATUS.md" move "%ROOT_DIR%\ML_ALGORITHMS_STATUS.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\PHASE_1_COMPLETION_REPORT.md" move "%ROOT_DIR%\PHASE_1_COMPLETION_REPORT.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\PHASE2_ACTIVATION_MODULES_CORE.md" move "%ROOT_DIR%\PHASE2_ACTIVATION_MODULES_CORE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\PLAN_INTEGRATION_KEYCLOAK.md" move "%ROOT_DIR%\PLAN_INTEGRATION_KEYCLOAK.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\PROJECT_SUMMARY.md" move "%ROOT_DIR%\PROJECT_SUMMARY.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\QUICKSTART_VERIFICATION.md" move "%ROOT_DIR%\QUICKSTART_VERIFICATION.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\README_OLD.md" move "%ROOT_DIR%\README_OLD.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\README_SECURITY.md" move "%ROOT_DIR%\README_SECURITY.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\RECAPITULATIF_COMPLET_PHASES_2_ET_3.md" move "%ROOT_DIR%\RECAPITULATIF_COMPLET_PHASES_2_ET_3.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\REDIS_CONFIGURATION.md" move "%ROOT_DIR%\REDIS_CONFIGURATION.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\REPONSE_COMPLETE.md" move "%ROOT_DIR%\REPONSE_COMPLETE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\REPONSE_QUESTION_UTILISATEUR.md" move "%ROOT_DIR%\REPONSE_QUESTION_UTILISATEUR.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\RESTRUCTURE_BACKEND.md" move "%ROOT_DIR%\RESTRUCTURE_BACKEND.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\RESTRUCTURE_GAVEURS_FRONTEND.md" move "%ROOT_DIR%\RESTRUCTURE_GAVEURS_FRONTEND.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\SECURITE_JWT_KEYCLOAK_COMPLETE.md" move "%ROOT_DIR%\SECURITE_JWT_KEYCLOAK_COMPLETE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\SESSION_COMPLETE_2024-12-24.md" move "%ROOT_DIR%\SESSION_COMPLETE_2024-12-24.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\SIMULATEURS_REALTIME_COMPLETE.md" move "%ROOT_DIR%\SIMULATEURS_REALTIME_COMPLETE.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\SIMULATORS_QUICKSTART.md" move "%ROOT_DIR%\SIMULATORS_QUICKSTART.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\SMS_SERVICE_FIX.md" move "%ROOT_DIR%\SMS_SERVICE_FIX.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\SUMMARY.md" move "%ROOT_DIR%\SUMMARY.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\TRAVAUX_REALISES.md" move "%ROOT_DIR%\TRAVAUX_REALISES.md" "%ARCHIVE_DIR%\"
if exist "%ROOT_DIR%\UPDATE_WINDOWS_SCRIPTS.md" move "%ROOT_DIR%\UPDATE_WINDOWS_SCRIPTS.md" "%ARCHIVE_DIR%\"

echo.
echo ========================================
echo   Nettoyage terminé !
echo ========================================
echo.
echo Fichiers archivés dans: %ARCHIVE_DIR%
echo.
echo Fichiers CONSERVÉS à la racine:
echo   - README.md (principal)
echo   - CLAUDE.md (instructions IA)
echo   - INDEX.md (nouveau index)
echo   - DEMARRAGE_RAPIDE.md
echo   - DEMARRAGE_SIMULATEURS.md
echo   - NOUVEAUX_SCRIPTS_README.md
echo   - NEXT_STEPS.md
echo   - CHANGELOG.md
echo   - PHASE_3_TESTS_RECAP.md
echo.
