#!/bin/bash
# SQAL Health Endpoints Test Script
# Tests all health check endpoints without starting the full backend

echo "================================================================================"
echo "SQAL HEALTH ENDPOINTS - MANUAL TEST GUIDE"
echo "Phase 5 - Priority 2: Testing Health Checks"
echo "================================================================================"
echo ""
echo "This script provides commands to test health endpoints."
echo "You need to start the backend first in another terminal."
echo ""
echo "================================================================================"
echo "STEP 1: Start the Backend"
echo "================================================================================"
echo ""
echo "Run in another terminal:"
echo "  cd /home/user/SQAL_TOF_AS7341/backend_new"
echo "  python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
echo ""
echo "Wait for: '✅ SQAL Backend fully started and ready!'"
echo ""
echo "================================================================================"
echo "STEP 2: Test Health Endpoints"
echo "================================================================================"
echo ""

# Check if backend is running
echo "Checking if backend is running on port 8000..."
if curl -s http://localhost:8000/ > /dev/null 2>&1; then
    echo "✅ Backend is running!"
    echo ""

    echo "================================================================================"
    echo "Test 1: Root Endpoint"
    echo "================================================================================"
    echo "curl http://localhost:8000/"
    echo ""
    curl -s http://localhost:8000/ | python3 -m json.tool
    echo ""

    echo "================================================================================"
    echo "Test 2: Liveness Probe (Is app alive?)"
    echo "================================================================================"
    echo "curl http://localhost:8000/health/live"
    echo ""
    curl -s http://localhost:8000/health/live | python3 -m json.tool
    echo ""

    echo "================================================================================"
    echo "Test 3: Readiness Probe (Can serve traffic?)"
    echo "================================================================================"
    echo "curl http://localhost:8000/health/ready"
    echo ""
    curl -s http://localhost:8000/health/ready | python3 -m json.tool
    echo ""

    echo "================================================================================"
    echo "Test 4: Startup Probe (Finished starting?)"
    echo "================================================================================"
    echo "curl http://localhost:8000/health/startup"
    echo ""
    curl -s http://localhost:8000/health/startup | python3 -m json.tool
    echo ""

    echo "================================================================================"
    echo "Test 5: Detailed Health Check"
    echo "================================================================================"
    echo "curl http://localhost:8000/health/detailed"
    echo ""
    curl -s http://localhost:8000/health/detailed | python3 -m json.tool
    echo ""

    echo "================================================================================"
    echo "Test 6: Circuit Breakers Status"
    echo "================================================================================"
    echo "curl http://localhost:8000/health/circuit-breakers"
    echo ""
    curl -s http://localhost:8000/health/circuit-breakers | python3 -m json.tool
    echo ""

    echo "================================================================================"
    echo "Test 7: Prometheus Metrics"
    echo "================================================================================"
    echo "curl http://localhost:8000/metrics | head -n 50"
    echo ""
    curl -s http://localhost:8000/metrics | head -n 50
    echo ""
    echo "... (truncated, showing first 50 lines)"
    echo ""

    echo "================================================================================"
    echo "✅ ALL ENDPOINT TESTS COMPLETED"
    echo "================================================================================"

else
    echo "❌ Backend is NOT running on port 8000"
    echo ""
    echo "Please start the backend first:"
    echo "  cd /home/user/SQAL_TOF_AS7341/backend_new"
    echo "  python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
    echo ""
    echo "Then run this script again."
    echo ""
    echo "================================================================================"
    echo "MANUAL TEST COMMANDS"
    echo "================================================================================"
    echo ""
    echo "Once backend is running, you can test manually with these commands:"
    echo ""
    echo "# Liveness (app alive?)"
    echo "curl http://localhost:8000/health/live | python3 -m json.tool"
    echo ""
    echo "# Readiness (can serve traffic?)"
    echo "curl http://localhost:8000/health/ready | python3 -m json.tool"
    echo ""
    echo "# Startup (finished starting?)"
    echo "curl http://localhost:8000/health/startup | python3 -m json.tool"
    echo ""
    echo "# Detailed health"
    echo "curl http://localhost:8000/health/detailed | python3 -m json.tool"
    echo ""
    echo "# Circuit breakers"
    echo "curl http://localhost:8000/health/circuit-breakers | python3 -m json.tool"
    echo ""
    echo "# Prometheus metrics"
    echo "curl http://localhost:8000/metrics | head -n 50"
    echo ""
fi

echo ""
echo "================================================================================"
echo "KUBERNETES INTEGRATION TEST"
echo "================================================================================"
echo ""
echo "These endpoints work with Kubernetes probes:"
echo ""
echo "apiVersion: v1"
echo "kind: Pod"
echo "spec:"
echo "  containers:"
echo "  - name: sqal-backend"
echo "    livenessProbe:"
echo "      httpGet:"
echo "        path: /health/live"
echo "        port: 8000"
echo "    readinessProbe:"
echo "      httpGet:"
echo "        path: /health/ready"
echo "        port: 8000"
echo "    startupProbe:"
echo "      httpGet:"
echo "        path: /health/startup"
echo "        port: 8000"
echo ""
